### ISSUE TITLE
国产大模型api

### ISSUE THREAD

**Issue by zhouyanzhong18** [FeiLiu36/EoH#10]
老师您好，请问在eoh中提到远程LLM + API（例如， GPT3.5, Deepseek, Gemini Pro) ，请问国产API例如千问、星火等可以用吗

**Comment by FeiLiu36** [comment]
您好，
+ 千问和星火等可能需要自己修改[API Interface的代码](https://github.com/FeiLiu36/EoH/tree/main/eoh/src/eoh/llm)
+ [Deepseek](https://www.deepseek.com/)也是国产大模型，使用很方便，性能也较好
