### ISSUE TITLE
关于EoH项目的三个问题

### ISSUE THREAD

**Issue by weijuntao503** [FeiLiu36/EoH#11]
作者您好，我有尝试跑通创建的EoH项目，但目前遇到几个问题想请教下：
1.对于user_tsp_gls的例子：哪行代码是表示基于EoH调用大模型生成的heuristic (即update_edge_distance) 进行训练？
2.对于user_tsp_gls的例子：是否给出了对Testing data的测试代码，如果有，我应该如何使用大模型生成的最佳heuristic进行评估测试（需跑哪个文件等）？
3. example文件夹中user_bp_online例子和bp_online例子的区别是什么？
期待能得到您的回复，感激不尽

**Comment by FeiLiu36** [comment]
您好，
> 哪行代码是表示基于EoH调用大模型生成的heuristic (即update_edge_distance) 进行训练

请查看 [这里](https://github.com/FeiLiu36/EoH/examples/user_tsp_gls/gls/gls_evol.py#L131)

> 是否给出了对Testing data的测试代码，如果有，我应该如何使用大模型生成的最佳heuristic进行评估测试（需跑哪个文件等）

Testing data 在[这个文件夹](https://github.com/FeiLiu36/EoH/tree/main/examples/user_tsp_gls/TestingData), 测试评估代码需要自己略微修改

> example文件夹中user_bp_online例子和bp_online例子的区别是什么

user_bp_online和bp_online本质是一样的，但是bp_online把问题内置到EoH的problem文件夹里面的代码里了，user_bp_online用了本地的问题代码，是如何用本地自定义问题的一个示例。

**Comment by weijuntao503** [comment]
非常感谢您的解答！关于第二个问题回答的链接似乎失效了，可以重新提供下吗？测试评估代码是在prob.py基础上进行修改吗？

**Comment by FeiLiu36** [comment]
您好，链接已更新。评估代码可以在Prob.py上修改。

**Comment by weijuntao503** [comment]
好的，非常感谢您的解答！
