### ISSUE TITLE
关于自己在EoH的框架下创建项目遇到的若干问题

### ISSUE THREAD

**Issue by nudtdyk** [FeiLiu36/EoH#12]
作者您好，看到您的论文深受启发，特别是利用大模型解决在线装箱问题。我尝试在您的代码框架下写自己拟解决的问题场景，但是遇到以下问题：
在readme中您提到了安装eoh，于是我首先在eoh/src/eoh/problems/optimization目录下依据bp_online构建自己问题的文件夹及相关py文件。同时修改了eoh/src/eoh/problems下的problems.py文件。然后通过pip install .安装eoh
同样我在EoH-main/examples下构建了对应文件夹及py文件，运行目录下的runEoH.py会遇到以下问题：
![image](https://github.com/user-attachments/assets/9fbe8cde-38a7-43a5-8787-42ffe778a9e0)
如图所示，创建初始种群为空，请问最可能出现问题的地方是哪儿。
烦请您空闲的时候帮我看一下问题所在处，谢谢！

**Comment by FeiLiu36** [comment]
您好，上述现象大概率的原因是本地写的prob.py或者prompt.py有问题。

建议按照如下步骤逐步验证部署自己的问题：

1）实现自己的prob.py 和 prompts.py

2）在本地先基于自己手动设计的heuristic 运行prob.py （此时不需要和大模型交互）。确保本地设计的prob.py没有问题

3)   在EoH debug模式下(exp_debug_mode = True)，单一线程运行, 能够观察生成的prompt和大模型的反馈。确保在手动设计的prompts 下大模型的反馈正常，是设计时期望的反馈。

4）确保上述都没有问题以后，再直接运行runEoH.py (此时还需要注意运行时间的限制，并行线程数目等)

**Comment by nudtdyk** [comment]
非常感谢您的回答，现在根据您的方法调试好了
