### ISSUE TITLE
大模型运行结果为空

### ISSUE THREAD

**Issue by nudtdyk** [FeiLiu36/EoH#13]
作者您好，前段时间阅读您的论文后大受启发，也想运用该框架解决自己的问题
但是，最近我发现LL无法根据prompt生成代码，于是测试了您的初始源码，发现现在也不能生成相应结果了，如下图所示：
![image](https://github.com/user-attachments/assets/7936abd7-8ca2-46e8-9d7f-eaa84318e1f6)
请问这是什么原因导致的呢，请您有空的时候帮忙回复一下，谢谢！

**Comment by FeiLiu36** [comment]
您好！感谢关注！
> 可能的问题如下：
1. 大模型能力不够强，采用一些能力足够的大模型如GPT3.5， Deepseek等
2. 种群太小导致初始解生成的时候由于随机性没有生成可行解

> 解决方案如下：
1. 将大模型设置为GPT3.5，Deepseek等
2. 将种群大小从4改成10
4. 如果还没有可行解，可以采用EoH的debug模式观察结果

**Comment by nudtdyk** [comment]
您好！十分感谢答复。

根据您的意见修改gpt为deepseek并修改种群大小后可以得到结果，但有以下的一些疑惑：

1. 之前使用deepseek，种群大小为4，可以获得较好的结果，但现在需要将种群大小修改为10才能得到结果，且效果没有之前的好
2. 请问这是否与在线大模型更新后，调用大模型生成代码校验不通过有关系呢？
3. 如果是这个原因，请问需要如何修改呢？
烦请您有空的时候帮忙解答一下，不胜感激！

**Comment by FeiLiu36** [comment]
您好，因为搜索框架是从大模型随机生成的算法开始搜索的，所以框架本身就有随机性，当种群规模比较小和迭代次数比较少的时候这个随机性会更高。
当种群大小和种群迭代次数足够时，这个随机性会大大减少。比如EoH论文里面一般1000+次评估能获得较好的效果。

**Comment by nudtdyk** [comment]
您好，再次感谢您的回复！
按照您的建议，我尝试使用采用EoH的debug模式，但是对于您源码中无论bp_online问题还是tsp问题，debug模式下采用deepseek等多种gpt都会报相同的错误，如下所示：
![image](https://github.com/user-attachments/assets/a6c1e8c5-1d12-4ded-897b-6b651efc18b7)
代码在debug模式下无法生成初始解，关闭debug模式，一些推理能力较强的gpt可以获得相应结果。

但是这种现象在我前一个月使用您的代码调用大模型api时都没出现过，请问您能告诉另外的解决方法吗？
抱歉又打扰您了，谢谢！

**Comment by FeiLiu36** [comment]
近一个月并没有大的代码更新，所以应该不存在结果突然差很多的问题。

我们本地测试了目前的版本，用deepseek模型，在online bin packing，结果正常，并不存在大量不可行算法和无法生成初始解的情况。

下面是我们的terminal输出：
![image](https://github.com/user-attachments/assets/68eaa215-1e6e-4e51-9e63-c34cd276a90e)



建议按照如下步骤double-check
1. 是否是库里面的EoH版本，是否自己做过修改
2. 是否用的默认的问题比如online bin packing, 是否自己修改过问题定义和prompt描述
3. 如果要用debug模式观察和检查中间过程，不要开多进程，把进程数设置为1

**Comment by nudtdyk** [comment]
十分感谢您的耐心解答！我明白问题所在了，再次感谢您！
