### ISSUE TITLE
请教代码迭代关键过程可视化的问题

### ISSUE THREAD

**Issue by nudtdyk** [FeiLiu36/EoH#14]
刘博士您好，首先十分感谢您开源论文代码及相应的指导，前面通过您的解答后对您所提算法框架有了更深的认知，目前已经开始进一步运用于自己亟需解决的组合优化问题。
现在也取得了一些初步效果，优化效果良好。
为了能够进一步优化代码效果，想学习您对代码迭代过程关键部分的一个可视化过程，如下所示：
![image](https://github.com/user-attachments/assets/209968ab-1c70-43f3-abcb-b1f558c6701c)

请问如何像您一样可以提取迭代轮数中，哪个策略对代码提升起到了关键作用？它又是修改的哪一部分？
十分抱歉再次打扰您了，麻烦您在有空的时候帮忙解答下这个问题，这对我十分重要，谢谢！

**Comment by FeiLiu36** [comment]
您好！

非常高兴听到已经获得了一定效果。
+ 上述可视化的过程目前还没有完全自动化起来
+ 如果只是需要收敛曲线可以通过results文件夹里面的历史记录来绘制
+ 如果要判断每个最优位置哪个策略对代码起到作用，需要添加代码到EoH搜索过程中去记录每个新代码\启发式算法是由哪个算子获得的
+ 如果要识别每一个地方的关键新增的代码\启发式片段，需要通过人工去观察结果来提取这些信息
+ 个人建议可以通过人工取观察结果来展示收敛中关键的几个新代码\启发式算法来添加到收敛曲线上增加展示效果和清晰度；至于哪个算子获得的可以不用展示，哪个算子的展示可能对于具体的应用场景可能没有那么重要；主要可能是展示清楚收敛过程中什么代码对解决目标问题带来一些新的思路和设计和收敛过程中能够不断出现新的设计。

谢谢！

**Comment by nudtdyk** [comment]
谢谢刘博士，十分感谢您的解答与建议，感激不尽！
