### ISSUE TITLE
柳老师您好，运训runeoh.py生成的程序，项目中的评估程序在哪，或者如何进行评估

### ISSUE THREAD

**Issue by Tender-sun** [FeiLiu36/EoH#2]
柳老师您好，关于代码复现，运行代码之后得到的结果算法在不同数据集上的评估程序如何运行，同时文中提到了m3 ，但是代码中删除了这一设计

**Comment by FeiLiu36** [comment]
> 如何评估

我们这周即将上传评估的insrtance和代码。

> m3

因为我们发现m3对于结果的影响比较小，所以没有加上去，后面会添加，如果不用m3, 结果也基本差不多。

**Comment by FeiLiu36** [comment]
[Constructive Heuristic for TSP](https://github.com/FeiLiu36/EoH/tree/main/examples/tsp_construct/evaluation) 和 [online bin packing](https://github.com/FeiLiu36/EoH/tree/main/examples/bp_online/evaluation) 问题的评估代码和测试算例已上传。后续会陆续更新其他问题，欢迎关注，谢谢！
