### ISSUE TITLE
Inquiry about the Open Sourcing of FSSP Code and Joining the Research Group

### ISSUE THREAD

**Issue by lgy0404** [FeiLiu36/EoH#4]
Hello EoH Team,

I am very impressed by your project "EoH: Evolution of Heuristics" and the innovative approach it brings to algorithm design using EC and LLMs. I am particularly interested in the application of EoH to the Flow Shop Scheduling Problem (FSSP) and noticed that the code for this part has not yet been shared in the repository.

Could you please provide any updates regarding when the FSSP code might be available for open sourcing? I am eager to explore this further and potentially contribute to its development.

Additionally, I am interested in joining the research group you mentioned. Could you provide more information on how to get involved or whom to contact?

Thank you for your time and effort in advancing this exciting field.

**Comment by FeiLiu36** [comment]
Hi! We will be uploading the results for FSSP+GLS and TSP+GLS, along with their evaluation code and instances, this week.

We have also created a WeChat group to share research on LLM for optimization. If you're interested, please email me (fliu36-c@my.cityu.edu.hk) your WeChat number so I can add you to the group.

Thank you!

**Comment by lgy0404** [comment]
Thank you for the update and the opportunity to join the WeChat group. I have sent you an email with my WeChat number for the group invitation.

Looking forward to contributing and collaborating in this innovative area!

**Comment by FeiLiu36** [comment]
Hi! The code for FSSP and TSP in the guided local search framework has been uploaded. Please check the new examples in [FSSP](https://github.com/FeiLiu36/EoH/tree/main/examples/user_fssp_gls) and [TSP](https://github.com/FeiLiu36/EoH/tree/main/examples/user_tsp_gls).
Thank you!

**Comment by lgy0404** [comment]
Hi @FeiLiu36 ,

Thank you for updating the FSSP and TSP code! I'll start exploring the new examples right away.
