### ISSUE TITLE
llm_api_endpoint

### ISSUE THREAD

**Issue by YangQiPeng1211** [FeiLiu36/EoH#5]

**Comment by FeiLiu36** [comment]
In your case, could you test the endpoint ```api.openai.com```?

**Comment by YangQiPeng1211** [comment]
yes, i already test the api_key, which can normally return

**Comment by FeiLiu36** [comment]
I mean the llm_api_endpoint should be set to "api.openai.com" instead of "https://api.openai.com/v1/chat/completions".

**Comment by YangQiPeng1211** [comment]
It didn`t work

**Comment by FeiLiu36** [comment]
Could I have the detailed settings and the terminal response.

**Comment by YangQiPeng1211** [comment]
ubuntu 22.04
python 3.11
openai 1.25.0
model gpt-3.5-turbo
![image](https://github.com/FeiLiu36/EoH/assets/92204327/f040dfd1-9a02-41f8-b170-de71a9f46b87)

**Comment by FeiLiu36** [comment]
It is weird, I can run it with Openai API using the same endpoint setting and model. 
I suggest the following solutions:
1. double check the network and VPN (if any), sometimes a proxy leads to network errors. 
2. use other APIs.

**Comment by YangQiPeng1211** [comment]
thanks
