### ISSUE TITLE
eoh遇到问题

### ISSUE THREAD

**Issue by wuyanzuwang** [FeiLiu36/EoH#6]
你好，我运行代码它说找不到我的setup文件，但是确实有这个文件了。然后我在cmd输入python setup.py install没有一点反应（我是window11系统）。请问能有什么解决办法嘛？我对这方面很感兴趣。希望得到回复，谢谢您！
![c3a0b408d4deea1b375a1f795559e4d](https://github.com/FeiLiu36/EoH/assets/170635529/623ddf6e-48d8-41e3-8153-12a09bc2ba67)

**Comment by FeiLiu36** [comment]
您好，谢谢关注！
可以尝试从shell 或者cmd 到setup.py 路径下运行，有可能是IDE路径问题。
