### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by Li-lab98** [FeiLiu36/EoH#9]
作者您好，我在运行程序时有如下两个问题：
1. 给的Online Bin Packing的例子里，运行完runEoH.py文件后，需要复制heuristic到heuristic.py这个文件，请问大模型生成的最佳heuristic在哪里可以找到？下面是我终端的运行结果：
--- 18 of 20 populations finished. Time Cost:  16.6 m
Pop Objs:  0.03854 0.03884 0.03914 0.03924 0.03934 
 OP: e1, [1 / 4] | Obj:  1.51524| Obj:  0.04095| Obj:  1.30506| Obj:  0.04306| Obj:  1.51454|
 OP: e2, [2 / 4] | Obj:  0.04226| Obj:  1.49613| Obj:  None| Obj:  None| Obj:  1.48063|
 OP: m1, [3 / 4] | Obj:  0.03984| Obj:  1.51534| Obj:  0.30416| Obj:  None| Obj:  0.03984|
 OP: m2, [4 / 4] | Obj:  0.03984| Obj:  0.06842| Obj:  0.04095| Obj:  0.04186| Obj:  1.50045|
--- 19 of 20 populations finished. Time Cost:  17.7 m
Pop Objs:  0.03854 0.03884 0.03914 0.03924 0.03934 
 OP: e1, [1 / 4] | Obj:  1.51534| Obj:  1.51524| Obj:  0.07345| Obj:  1.49764| Obj:  1.5079|
 OP: e2, [2 / 4] | Obj:  0.03833| Obj:  0.08311| Obj:  1.50025| Obj:  None| Obj:  0.04226|
 OP: m1, [3 / 4] | Obj:  0.03994| Obj:  0.03984| Obj:  1.51534| Obj:  0.04226| Obj:  0.03924|
 OP: m2, [4 / 4] | Obj:  0.04819| Obj:  1.51534| Obj:  0.04276| Obj:  1.47892| Obj:  0.06127|
--- 20 of 20 populations finished. Time Cost:  18.6 m
Pop Objs:  0.03833 0.03854 0.03884 0.03914 0.03924 
> End of Evolution! 
----------------------------------------- 
---     EoH successfully finished !   ---
-----------------------------------------
2. 请问如何复现论文中的结果？论文第五页中的最后“In our experiments, the number of generations in EoH for  all problems is set to 20.”这个参数在哪里设置？下面是我设置的参数，请看下是不是和论文中的参数设置一致
paras.set_paras(method = "eoh",    # ['ael','eoh']
                problem = "bp_online", #['tsp_construct','bp_online']
                llm_api_endpoint = "----", # set your LLM endpoint
                llm_api_key = "sk----",   # set your key
                llm_model = "gpt-3.5-turbo",
                ec_pop_size = 5, # number of samples in each population
                ec_n_pop = 20,  # number of populations
                exp_n_proc = 5,  # multi-core parallel
                exp_debug_mode = False)

刚接触这个领域不久，问题比较低级，还请见谅！

**Comment by FeiLiu36** [comment]
> 请问大模型生成的最佳heuristic在哪里可以找到

在results 文件夹里面，
+ results/pops 里面包含优化过程中所有的种群(一个文件一个种群)，
+ results/pops_best 里面包含每个种群中最优的heuristic，

取最后一个种群的最优heuristic就是搜索过程中找到的最优的heuristic。

> the number of generations in EoH for all problems is set to 20.”这个参数在哪里设置

ec_n_pop 是种群的generation个数（论文中设置为20），ec_pop_size 是种群中heuristic 个数（论文中设置为20）

**Comment by Li-lab98** [comment]
明白了，谢谢您的回复
